# Generated by Django 5.1.4 on 2024-12-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Circuit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("length_km", models.FloatField()),
                ("turns", models.IntegerField()),
                ("lap_record", models.CharField(max_length=255)),
            ],
        ),
    ]
